algo:
  ['PolicyGradient', 'NaturalPG']
env_id:
  ['SafetyAntVelocity-v4']
logger_cfgs:use_wandb:
  [False]
train_cfgs:vector_env_nums:
  [2]
train_cfgs:torch_threads:
  [1]
train_cfgs:total_steps:
  1024
algo_cfgs:update_cycle:
  512
seed:
  [0]
