name: ci

on:
  push:
    branches:
      - main
  pull_request:
  # Allow to trigger the workflow manually
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          update-environment: true

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install omnisafe
        run: |
          python -m pip install -vvv --editable '.[lint]'

      - name: Install safety_gymnasium
        run: |
          python -m pip install -vvv --editable 'envs/safety-gymnasium'

      - name: pre-commit
        run: |
          python -m pre_commit run --all-files

      # - name: pylint
      #   run: |
      #     python -m pylint omnisafe

      - name: isort and black
        run: |
          python -m isort --check omnisafe
          python -m black --check omnisafe
