name: ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  # Allow to trigger the workflow manually
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          update-environment: true

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools

      - name: Install Safety-Gymnasium
        run: |
          python -m pip install -vvv --editable 'envs/safety-gymnasium'

      - name: Install OmniSafe
        run: |
          python -m pip install -vvv --editable '.[lint]'

      - name: pre-commit
        run: |
          make pre-commit

      - name: flake8
        run: |
          make flake8

      - name: pylint
        run: |
          make pylint

      - name: isort and black
        run: |
          make py-format

      - name: addlicense
        run: |
          make addlicense

      # TODO: enable this when ready
      # - name: mypy
      #   run: |
      #     make mypy

      - name: Install dependencies
        run: |
          python -m pip install -r docs/requirements.txt

      # TODO: enable this when ready
      # - name: docstyle
      #   run: |
      #     make docstyle

      - name: spelling
        run: |
          make spelling

      - name: Install pytest
        run: |
          python -m pip install -r tests/requirements.txt

      - name: Run tests and collect coverage
        run: |
          pytest tests/test_buffer.py --cov

      - name: Run tests and collect coverage
        run: |
          pytest tests/test_safety_gym_envs.py --cov

      - name: Run tests and collect coverage
        run: |
          pytest tests/test_policy.py --cov

      - name: Upload coverage reports to Codecov
        run: |
          # Replace `linux` below with the appropriate OS
          # Options are `alpine`, `linux`, `macos`, `windows`
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN=634594d3-0416-4632-ab6a-3bf34a8c0af3}
