name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: pip install -r tests/requirements.txt
    - name: Run tests and collect coverage
      run: pytest test_buffer.py --cov
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${634594d3-0416-4632-ab6a-3bf34a8c0af3
